# Generated by Django 4.0.4 on 2022-05-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0002_node_x_node_y_topology_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='status',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Finised', 'Finished')], max_length=40),
        ),
        migrations.AlterField(
            model_name='node',
            name='x',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='node',
            name='y',
            field=models.FloatField(default=1),
        ),
    ]
